async function goalStats(){const s=await settings(),tx=await getAll('transactions'),as=await assetsStats();const cash=tx.filter(t=>t.kind==='car_saving').reduce((a,t)=>a+Number(t.amount||0),0);const phoneNet=(s.phoneReplacementCost===null||s.phoneReplacementCost===''||Number(s.phoneReplacementCost)<0)?0:Math.max(0,as.phone-Number(s.phoneReplacementCost||0));const total=cash+as.gold+phoneNet;return{cash,gold:as.gold,phoneGross:as.phone,phoneNet,total,target:Number(s.carPersonalTarget||500000000),remaining:Math.max(0,Number(s.carPersonalTarget||0)-total),progress:Number(s.carPersonalTarget||0)?total/Number(s.carPersonalTarget):0,phonePending:s.phoneReplacementCost===null||s.phoneReplacementCost===''}}
async function netWorth(){const accounts=await getAll('accounts');let cash=0;for(const a of accounts)cash+=await accountBalance(a);const as=await assetsStats(),ds=await debtStats(),cs=await claimsStats();const tx=await getAll('transactions');const savings=tx.filter(t=>['car_saving','savings'].includes(t.kind)).reduce((a,t)=>a+Number(t.amount||0),0);return cash+as.total+savings+cs.remaining-ds.remaining}
async function plannedInstallment(month){const x=(await getAll('installments')).find(i=>i.month===month);return Number(x?.amount||0)}

async function generateInsights(month){const s=await settings(),m=await monthlyData(month),d=await debtStats(),g=await goalStats(),plan=await plannedInstallment(month);const insights=[];const coreNeed=Number(s.essentialBudget||0)+plan+Number(s.insuranceMonthlyReserve||0);const safeFree=Math.max(0,Math.min(Number(s.freeMoneyTarget||0),m.coreIncome-coreNeed));
 if(m.coreIncome===0)insights.push({level:'warning',tag:'داده ناکافی',title:'هنوز درآمد حقوق/پورسانت این ماه ثبت نشده',text:'بعد از ثبت حقوق و پورسانت، برنامه می‌تواند ظرفیت واقعی پول آزاد و سهم هدف ماشین را محاسبه کند.'});
 else if(m.coreIncome<coreNeed)insights.push({level:'danger',tag:'فشار نقدینگی',title:`برای تعهدات اصلی حدود ${shortMoney(coreNeed-m.coreIncome)} کسری داری`,text:'در این ماه پول آزاد و خریدهای اختیاری باید بعد از پوشش هزینه ضروری، قسط و ذخیره بیمه قرار بگیرند.'});
 else insights.push({level:'success',tag:'پوشش تعهدات',title:'حقوق و پورسانت تعهدات اصلی این ماه را پوشش می‌دهد',text:`پس از بودجه ضروری، قسط برنامه‌ای و ذخیره بیمه، ظرفیت اولیه حدود ${money(Math.max(0,m.coreIncome-coreNeed))} است.`});
 if(m.free>safeFree)insights.push({level:'warning',tag:'پول آزاد',title:'خرج آزاد از سطح امن این ماه بالاتر رفته',text:`با درآمد ثبت‌شده، پول آزاد امن حدود ${money(safeFree)} است؛ خرج آزاد ثبت‌شده ${money(m.free)} بوده است.`});
 if(d.remaining>0){if(m.vpnNet>0)insights.push({level:'success',tag:'VPN → بدهی',title:`سود خالص VPN این ماه ${money(m.vpnNet)} است`,text:`طبق برنامه، تا سقف بدهی باقی‌مانده (${money(d.remaining)}) می‌توانی این مبلغ را برای تسویه بدهی نگه داری. پرداخت بدهی ثبت‌شده با منبع VPN این ماه ${money(m.vpnDebtPay)} است.`});else insights.push({level:'warning',tag:'VPN',title:'این ماه هنوز سود خالص مثبت VPN ثبت نشده',text:'هدف فعلی این جریان درآمدی، کمک به تسویه بدهی است؛ فروش و هزینه VPN را جدا ثبت کن تا سود واقعی مشخص شود.'})}
 else insights.push({level:'success',tag:'بدهی',title:'بدهی ثبت‌شده تسویه شده',text:'از این نقطه، جریان خالص VPN می‌تواند به‌جای بدهی مستقیماً به صندوق ماشین هدایت شود.'});
 const elapsed=Math.max(1,monthIndex(month)-monthIndex('1405/07')+1),pace=clamp(elapsed/Number(s.carMonths||6),0,1);if(g.progress+0.03<pace)insights.push({level:'warning',tag:'هدف ماشین',title:'پیشرفت هدف ماشین از خط زمانی شش‌ماهه عقب‌تر است',text:`پیشرفت فعلی ${pct(g.progress*100)} و خط زمانی تقریبی ${pct(pace*100)} است. این شاخص فقط سرمایه قابل‌استفاده ثبت‌شده را حساب می‌کند.`});else insights.push({level:'success',tag:'هدف ماشین',title:'مسیر هدف ماشین قابل مشاهده است',text:`سرمایه قابل محاسبه فعلی ${money(g.total)} از هدف ${money(g.target)} است.`});
 const scenario=m.variable===0?'ثبت‌نشده':(m.variable<=Number(s.variableBad||0)*1.1?'ضعیف':m.variable<=Number(s.variableAverage||0)*1.15?'متوسط':'خوب');if(m.variable>0)insights.push({level:scenario==='ضعیف'?'warning':'success',tag:'سناریوی درآمد',title:`درآمد متغیر این ماه در محدوده «${scenario}» قرار گرفته`,text:`درآمد متغیر ثبت‌شده ${money(m.variable)} است؛ حدود مرجع فعلی: ضعیف ${money(s.variableBad)}، متوسط ${money(s.variableAverage)} و خوب ${money(s.variableBest)}.`});
 if(g.phonePending)insights.push({level:'warning',tag:'دارایی گوشی',title:'ارزش خالص گوشی هنوز وارد هدف ماشین نشده',text:'برای جلوگیری از بیش‌برآورد، تا وقتی بودجه گوشی جایگزین را در تنظیمات وارد نکنی، ارزش ۱۶۰ میلیونی گوشی در پیشرفت هدف ماشین حساب نمی‌شود.'});
 if(Number(s.goldPrice||0)===0)insights.push({level:'warning',tag:'قیمت طلا',title:'قیمت روز طلا هنوز تنظیم نشده',text:'پس از اتصال منبع قیمت یا ورود دستی، ارزش ۶ گرم طلا به‌صورت خودکار در هدف ماشین محاسبه می‌شود.'});
 return insights.slice(0,7)}
function monthIndex(m){const [y,mo]=toEn(m).split('/').map(Number);return y*12+mo}

async function render(){if(!state.unlocked)return renderLock();const s=await settings();applyTheme(s.theme);let body='';if(state.view==='home')body=await viewHome();else if(state.view==='transactions')body=await viewTransactions();else if(state.view==='analytics')body=await viewAnalytics();else if(state.view==='more')body=await viewMore();else if(state.view==='vpn')body=await viewVPN();else if(state.view==='car')body=await viewCar();else if(state.view==='accounts')body=await viewAccounts();else if(state.view==='debts')body=await viewDebts();else if(state.view==='assets')body=await viewAssets();else if(state.view==='claims')body=await viewClaims();else if(state.view==='installments')body=await viewInstallments();else if(state.view==='settings')body=await viewSettings();app.innerHTML=shell(body);bindCommon()}
function shell(body){const titles={home:'مدیریت مالی',transactions:'تراکنش‌ها',analytics:'تحلیل مالی',more:'بیشتر',vpn:'VPN',car:'هدف ماشین',accounts:'حساب‌ها',debts:'بدهی‌ها',assets:'سرمایه‌ها',claims:'مطالبات',installments:'اقساط',settings:'تنظیمات'};return `<div class="app-shell"><header class="topbar"><div><button class="chip" data-action="month" style="padding:6px 10px;font-size:10px">${monthLabel(state.month)}⌄</button><h1>${titles[state.view]||'مدیریت مالی'}</h1></div><button class="icon-btn" data-action="theme" aria-label="تم">◐</button></header><main class="main">${body}</main>${bottomNav()}</div>`}

function openMonthPicker(){
 const months=Array.from({length:36},(_,i)=>nextJMonth('1405/07',i));
 document.body.insertAdjacentHTML('beforeend',`<div class="sheet-backdrop" id="monthSheet"><div class="sheet"><div class="sheet-handle"></div><h2>انتخاب ماه گزارش</h2><div class="chip-row" style="flex-wrap:wrap;overflow:visible">${months.map(m=>`<button class="chip ${m===state.month?'active':''}" data-month="${m}">${monthLabel(m)}</button>`).join('')}</div></div></div>`);
 const sh=document.getElementById('monthSheet');sh.onclick=e=>{if(e.target===sh)sh.remove()};sh.querySelectorAll('[data-month]').forEach(b=>b.onclick=()=>{state.month=b.dataset.month;sh.remove();render()});
}
