function bottomNav(){return `<nav class="bottom-nav"><div class="nav-inner"><button class="nav-btn ${state.view==='home'?'active':''}" data-view="home"><b>⌂</b>خانه</button><button class="nav-btn ${state.view==='transactions'?'active':''}" data-view="transactions"><b>≡</b>تراکنش</button><button class="nav-btn add" data-action="quick">＋</button><button class="nav-btn ${state.view==='analytics'?'active':''}" data-view="analytics"><b>⌁</b>تحلیل</button><button class="nav-btn ${['more','vpn','car','accounts','debts','assets','claims','installments','settings'].includes(state.view)?'active':''}" data-view="more"><b>•••</b>بیشتر</button></div></nav>`}
function bindCommon(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render()});document.querySelector('[data-action="quick"]')?.addEventListener('click',()=>openQuick());document.querySelector('[data-action="month"]')?.addEventListener('click',openMonthPicker);document.querySelector('[data-action="theme"]')?.addEventListener('click',async()=>{const current=document.documentElement.dataset.theme;await saveSettingsPatch({theme:current==='dark'?'light':'dark'});render()})}

async function viewHome(){const m=await monthlyData(state.month),day=await dailyData(gregToJalali()),ds=await debtStats(),gs=await goalStats(),nw=await netWorth(),cs=await claimsStats(),acc=await getAll('accounts');let bank=0;for(const a of acc)bank+=await accountBalance(a);const s=await settings();const goldStatus=s.lastGoldUpdate?`آخرین بروزرسانی ${toFa(s.lastGoldUpdate.replace('T',' ').slice(0,16))}`:'هنوز بروزرسانی نشده';return `
<div class="hero-card"><div class="hero-label">ارزش خالص تقریبی</div><div class="hero-value">${money(nw)}</div><div class="hero-sub"><span>${monthLabel(state.month)}</span><span>درآمد ماه ${money(m.income)}</span><span>بدهی مانده ${money(ds.remaining)}</span></div></div>
<div class="section-title"><h2>نمای سریع</h2><small>${monthLabel(state.month)}</small></div>
<div class="grid metrics"><div class="card metric"><div class="icon">↗</div><label>درآمد دریافت‌شده</label><strong>${shortMoney(m.income)}</strong><small>حقوق، پورسانت، VPN و سایر</small></div><div class="card metric"><div class="icon">↘</div><label>هزینه و تعهدات</label><strong>${shortMoney(m.spending)}</strong><small>بدون انتقال به پس‌انداز</small></div><div class="card metric"><div class="icon">◎</div><label>موجودی حساب‌ها</label><strong>${shortMoney(bank)}</strong><small>${toFa(acc.length)} حساب ثبت‌شده</small></div><div class="card metric"><div class="icon">⌛</div><label>مطالبات باز</label><strong>${shortMoney(cs.remaining)}</strong><small>وصول‌نشده</small></div></div>
<div class="section-title"><h2>هدف ماشین</h2><button class="chip active" data-go="car">جزئیات</button></div>
<div class="card goal-card"><div style="display:flex;justify-content:space-between;gap:12px"><div><div class="hint">سرمایه قابل محاسبه</div><strong style="font-size:22px">${money(gs.total)}</strong></div><div class="badge">هدف ${shortMoney(gs.target)}</div></div><div class="progress"><i style="width:${clamp(gs.progress*100,0,100)}%"></i></div><div class="progress-row"><span>${pct(gs.progress*100)} پیشرفت</span><span>${money(gs.remaining)} باقی‌مانده</span></div></div>
<div class="section-title"><h2>امروز</h2><small>${toFa(gregToJalali())}</small></div><div class="card"><div class="kpi-line"><span>ورودی امروز</span><strong class="success-text">${money(day.incoming)}</strong></div><div class="kpi-line"><span>خروجی امروز</span><strong class="danger-text">${money(day.outgoing)}</strong></div><div class="kpi-line"><span>خالص تغییر امروز</span><strong>${money(day.net)}</strong></div></div><div class="section-title"><h2>ثبت سریع</h2></div><div class="quick-actions"><button class="quick" data-preset="income_commission"><span>＋</span>پورسانت</button><button class="quick" data-preset="expense_essential"><span>−</span>هزینه</button><button class="quick" data-preset="income_vpn"><span>V</span>فروش VPN</button><button class="quick" data-preset="debt_payment"><span>✓</span>بدهی</button></div>
<div class="section-title"><h2>طلای ۱۸ عیار</h2><button class="chip" id="goldRefresh">بروزرسانی</button></div><div class="card gold-card"><div class="gold-price">${Number(s.goldPrice)?money(s.goldPrice)+'/گرم':'قیمت ثبت نشده'}</div><div class="gold-meta"><span class="online-dot ${navigator.onLine?'':'offline-dot'}"></span>${navigator.onLine?'آنلاین':'آفلاین'} · ${goldStatus}</div><div class="kpi-line"><span>ارزش ۶ گرم طلا</span><strong>${money(gs.gold)}</strong></div></div>`}

async function viewTransactions(){const all=(await getAll('transactions')).sort((a,b)=>(b.date+b.createdAt).localeCompare(a.date+a.createdAt));const rows=all.slice(0,100).map(t=>{const meta=kindMeta[t.kind]||['تراکنش','',signedAmount(t)>=0?'in':'out'];return `<button class="row" data-tx-id="${t.id}" style="width:100%;text-align:right;color:inherit"><div class="row-icon">${meta[2]==='in'?'＋':'−'}</div><div class="row-main"><strong>${esc(transactionName(t.kind))}${t.note?' · '+esc(t.note):''}</strong><small>${toFa(t.date)} · ${esc(meta[1])}</small></div><div class="amount ${meta[2]}">${meta[2]==='in'?'+':'−'} ${shortMoney(t.amount)}</div></button>`}).join('');return `<div class="chip-row"><button class="chip active">همه</button><button class="chip">درآمد</button><button class="chip">هزینه</button><button class="chip">VPN</button><button class="chip">بدهی</button></div><div class="list">${rows||'<div class="empty"><b>هنوز تراکنشی ثبت نشده</b>از دکمه + برای ثبت سریع استفاده کن.</div>'}</div>`}

async function viewVPN(){const m=await monthlyData(state.month),d=await debtStats();const usable=Math.max(0,m.vpnNet-m.vpnDebtPay);return `<div class="card goal-card"><div class="hint">سود خالص VPN در ${monthLabel(state.month)}</div><div class="hero-value" style="color:var(--ink);font-size:28px">${money(m.vpnNet)}</div><div class="progress-row"><span>فروش ${money(m.vpnIncome)}</span><span>هزینه ${money(m.vpnCost)}</span></div></div><div class="section-title"><h2>برنامه بدهی</h2></div><div class="card"><div class="kpi-line"><span>بدهی باقی‌مانده</span><strong>${money(d.remaining)}</strong></div><div class="kpi-line"><span>پرداخت بدهی از VPN این ماه</span><strong>${money(m.vpnDebtPay)}</strong></div><div class="kpi-line"><span>سود VPN هنوز تخصیص‌نیافته</span><strong>${money(usable)}</strong></div></div><div class="section-title"><h2>عملیات سریع</h2></div><div class="two"><button class="primary" data-preset="income_vpn">ثبت فروش VPN</button><button class="secondary" data-preset="expense_vpn">ثبت هزینه VPN</button></div><button class="primary full" style="margin-top:10px" data-preset="debt_payment" data-fund-source="vpn">ثبت پرداخت بدهی از VPN</button><div class="insight success" style="margin-top:14px"><span class="tag">قاعده فعلی</span><h3>VPN موتور تسویه بدهی است</h3><p>تا زمانی که بدهی صفر نشده، سود خالص VPN برای بدهی نگه داشته می‌شود. بعد از تسویه، همین جریان به صندوق ماشین منتقل می‌شود.</p></div>`}

async function viewCar(){const g=await goalStats(),s=await settings();return `<div class="hero-card"><div class="hero-label">هدف شخصی خرید ماشین</div><div class="hero-value">${money(g.target)}</div><div class="hero-sub"><span>بازه قیمت ماشین ${shortMoney(s.carGoalMin)} تا ${shortMoney(s.carGoalMax)}</span><span>افق ${toFa(s.carMonths)} ماهه</span></div></div><div class="section-title"><h2>سرمایه قابل استفاده</h2></div><div class="card"><div class="kpi-line"><span>صندوق نقدی ماشین</span><strong>${money(g.cash)}</strong></div><div class="kpi-line"><span>ارزش ۶ گرم طلا</span><strong>${money(g.gold)}</strong></div><div class="kpi-line"><span>گوشی قابل فروش</span><strong>${money(g.phoneGross)}</strong></div><div class="kpi-line"><span>خالص گوشی پس از جایگزین</span><strong>${g.phonePending?'نامشخص':money(g.phoneNet)}</strong></div><div class="kpi-line"><span>کالای در گردش</span><strong>در هدف ماشین حساب نمی‌شود</strong></div></div><div class="section-title"><h2>پیشرفت</h2></div><div class="card goal-card"><strong style="font-size:23px">${money(g.total)}</strong><div class="progress"><i style="width:${clamp(g.progress*100,0,100)}%"></i></div><div class="progress-row"><span>${pct(g.progress*100)}</span><span>${money(g.remaining)} مانده</span></div></div><button class="primary full" style="margin-top:14px" data-preset="car_saving">افزودن به صندوق ماشین</button>${g.phonePending?'<div class="insight warning" style="margin-top:12px"><span class="tag">نیاز به تنظیم</span><h3>بودجه گوشی جایگزین را وارد کن</h3><p>تا آن زمان ارزش گوشی برای هدف ماشین صفر در نظر گرفته می‌شود تا برنامه بیش‌برآورد نکند.</p></div>':''}`}

async function viewAnalytics(){
 const months=Array.from({length:6},(_,i)=>nextJMonth(state.month,i-5)),data=[];for(const mo of months)data.push([mo,await monthlyData(mo)]);
 const max=Math.max(1,...data.flatMap(x=>[x[1].income,x[1].spending]));
 const bars=data.map(([mo,x])=>`<div class="bar-wrap"><em>${shortMoney(x.income)}</em><div style="height:150px;display:flex;align-items:end;justify-content:center;gap:4px"><div class="bar" style="height:${Math.max(3,x.income/max*150)}px;width:18px"></div><div class="bar" style="height:${Math.max(3,x.spending/max*150)}px;width:18px;opacity:.38"></div></div><small>${monthLabel(mo).split(' ')[0]}</small></div>`).join('');
 const insights=await generateInsights(state.month),m=await monthlyData(state.month),saving=m.carSaving+m.saving+m.investment;
 const expense=m.essential+m.free+m.vpnCost+m.insurance,total=Math.max(1,expense+m.installment+m.debtPay+saving),p1=expense/total*100,p2=p1+m.installment/total*100,p3=p2+m.debtPay/total*100;
 const donut=`conic-gradient(var(--blue) 0 ${p1}%, #77aaff ${p1}% ${p2}%, var(--warning) ${p2}% ${p3}%, var(--success) ${p3}% 100%)`;
 return `<div class="section-title"><h2>تحلیل خودکار</h2><small>کاملاً آفلاین</small></div>${insights.map(i=>`<div class="insight ${i.level}"><span class="tag">${i.tag}</span><h3>${i.title}</h3><p>${i.text}</p></div>`).join('')}
 <div class="section-title"><h2>روند ۶ ماهه جریان نقد</h2></div><div class="card chart-card"><div class="bars">${bars}</div><div class="progress-row" style="margin-top:12px"><span>آبی: درآمد</span><span>کم‌رنگ: هزینه و تعهدات</span></div></div>
 <div class="section-title"><h2>ترکیب خروجی این ماه</h2></div><div class="card"><div class="donut-wrap"><div class="donut" style="background:${donut}"></div><div class="legend"><div class="legend-row"><span><i class="legend-dot" style="background:var(--blue)"></i>هزینه‌ها</span><strong>${shortMoney(expense)}</strong></div><div class="legend-row"><span><i class="legend-dot" style="background:#77aaff"></i>اقساط</span><strong>${shortMoney(m.installment)}</strong></div><div class="legend-row"><span><i class="legend-dot" style="background:var(--warning)"></i>بدهی</span><strong>${shortMoney(m.debtPay)}</strong></div><div class="legend-row"><span><i class="legend-dot" style="background:var(--success)"></i>هدف/پس‌انداز</span><strong>${shortMoney(saving)}</strong></div></div></div></div>
 <div class="section-title"><h2>شاخص‌های ماه</h2></div><div class="card"><div class="kpi-line"><span>نسبت هزینه و تعهدات به درآمد</span><strong>${m.income?pct(m.spending/m.income*100):'—'}</strong></div><div class="kpi-line"><span>نرخ پس‌انداز/ماشین/سرمایه‌گذاری</span><strong>${m.income?pct(saving/m.income*100):'—'}</strong></div><div class="kpi-line"><span>سود خالص VPN</span><strong>${money(m.vpnNet)}</strong></div><div class="kpi-line"><span>درآمد متغیر</span><strong>${money(m.variable)}</strong></div></div>`
}

async function viewMore(){return `<div class="grid"><button class="card" data-go="vpn" style="text-align:right;border:1px solid var(--line)"><div class="row-icon">V</div><h3>VPN</h3><p class="hint">فروش، هزینه، سود خالص و بدهی</p></button><button class="card" data-go="car" style="text-align:right;border:1px solid var(--line)"><div class="row-icon">🚗</div><h3>هدف ماشین</h3><p class="hint">پیشرفت تا ۵۰۰ میلیون</p></button><button class="card" data-go="accounts" style="text-align:right;border:1px solid var(--line)"><div class="row-icon">▣</div><h3>حساب‌ها</h3><p class="hint">بانک و پول نقد</p></button><button class="card" data-go="debts" style="text-align:right;border:1px solid var(--line)"><div class="row-icon">⇣</div><h3>بدهی‌ها</h3><p class="hint">مانده و تسویه</p></button><button class="card" data-go="installments" style="text-align:right;border:1px solid var(--line)"><div class="row-icon">◷</div><h3>اقساط</h3><p class="hint">برنامه چهار ماه اول</p></button><button class="card" data-go="claims" style="text-align:right;border:1px solid var(--line)"><div class="row-icon">⌛</div><h3>مطالبات</h3><p class="hint">طلب‌های وصول‌نشده</p></button><button class="card" data-go="assets" style="text-align:right;border:1px solid var(--line)"><div class="row-icon">◆</div><h3>سرمایه‌ها</h3><p class="hint">طلا، گوشی و کالا</p></button><button class="card" data-go="settings" style="text-align:right;border:1px solid var(--line)"><div class="row-icon">⚙</div><h3>تنظیمات</h3><p class="hint">برنامه مالی، امنیت و طلا</p></button></div>`}

async function viewAccounts(){const as=await getAll('accounts');const rows=[];for(const a of as){rows.push(`<div class="row"><div class="row-icon">▣</div><div class="row-main"><strong>${esc(a.title)}</strong><small>${esc(a.type||'حساب')} · افتتاحیه ${money(a.opening||0)}</small></div><div class="amount in">${money(await accountBalance(a))}</div></div>`)}return `<button class="primary full" id="addAccount">افزودن حساب</button><div class="list" style="margin-top:12px">${rows.join('')||'<div class="empty"><b>حسابی ثبت نشده</b>موجودی اول مهر را وقتی مشخص شد، اینجا وارد کن.</div>'}</div>`}
async function viewDebts(){const d=await debtStats(),ds=await getAll('debts');return `<div class="hero-card"><div class="hero-label">بدهی باقی‌مانده</div><div class="hero-value">${money(d.remaining)}</div><div class="hero-sub"><span>اصل ${money(d.opening)}</span><span>پرداخت‌شده ${money(d.paid)}</span></div></div><div class="section-title"><h2>بدهی‌ها</h2><button class="chip" id="addDebt">افزودن</button></div><div class="list">${ds.map(x=>`<div class="row"><div class="row-icon">⇣</div><div class="row-main"><strong>${esc(x.title)}</strong><small>${esc(x.note||'')}</small></div><strong>${money(x.opening)}</strong></div>`).join('')}</div><button class="primary full" style="margin-top:14px" data-preset="debt_payment">ثبت پرداخت بدهی</button>`}
