 document.getElementById('setupFace')?.addEventListener('click',setupFaceID);
 document.getElementById('changePin')?.addEventListener('click',()=>setupPin(true));
 document.getElementById('backupBtn')?.addEventListener('click',backupData);
 document.getElementById('restoreBtn')?.addEventListener('click',()=>document.getElementById('restoreFile').click());
 document.getElementById('restoreFile')?.addEventListener('change',e=>restoreData(e.target.files[0]));
 const face=document.getElementById('faceStatus');if(face)kvGet('faceCredential').then(x=>face.textContent=x?'فعال':'غیرفعال');
}
const _render=render;render=async function(){await _render();if(state.unlocked)bindViewSpecific()}

async function updateGold(force=false){const s=await settings();if(!navigator.onLine){toast('آفلاین هستی؛ آخرین قیمت ذخیره‌شده نمایش داده می‌شود');return}if(!s.goldApiUrl){toast('ابتدا آدرس API قیمت طلا را در تنظیمات وارد کن');return}try{let url=s.goldApiUrl;if(url.includes('{KEY}'))url=url.replace('{KEY}',encodeURIComponent(s.goldApiKey||''));const headers={Accept:'application/json'};if(s.goldApiKey&&!s.goldApiUrl.includes('{KEY}'))headers[s.goldApiHeader||'X-API-Key']=s.goldApiKey;const r=await fetch(url,{headers,cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);const j=await r.json();let p=findGoldPrice(j);if(!p||!isFinite(p))throw Error('قیمت در پاسخ پیدا نشد');if(s.goldApiUnit==='rial')p/=10;p=Math.round(p);const now=new Date().toISOString();await saveSettingsPatch({goldPrice:p,lastGoldUpdate:now});await put('goldHistory',{id:todayISO(),price:p,at:now});toast('قیمت طلا بروزرسانی شد');render()}catch(e){console.error(e);toast('بروزرسانی طلا ناموفق بود؛ آخرین قیمت حفظ شد')}}
function findGoldPrice(j){const candidates=[j?.data?.prices?.geram18?.current,j?.data?.sell,j?.data?.buy,j?.prices?.geram18?.current,j?.geram18?.current,j?.geram18?.price];for(const x of candidates){const n=Number(String(x??'').replace(/[,٬]/g,''));if(n>10000)return n}const rows=j?.rows||j?.data?.rows||j?.items||j?.data?.items;if(Array.isArray(rows)){const r=rows.find(x=>x.symbol==='geram18'||x.key==='geram18'||String(x.title||'').includes('18'));if(r){const x=r.price?.value??r.price??r.current??r.value;const n=Number(String(x??'').replace(/[,٬]/g,''));if(n>10000)return n}}return 0}
async function dailyGoldUpdate(){const s=await settings();if(!s.goldApiUrl||!navigator.onLine)return;const last=(s.lastGoldUpdate||'').slice(0,10);if(last!==todayISO())await updateGold(false)}

async function sha256(s){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return b64(new Uint8Array(b))}
function b64(bytes){let s='';bytes.forEach(b=>s+=String.fromCharCode(b));return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function unb64(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const x=atob(s);return Uint8Array.from(x,c=>c.charCodeAt(0))}
function randomBytes(n=32){const a=new Uint8Array(n);crypto.getRandomValues(a);return a}
async function setupPin(changing=false){return new Promise(resolve=>{let pin='';document.body.insertAdjacentHTML('beforeend',`<div class="sheet-backdrop" id="pinSheet"><div class="sheet" style="max-width:430px;text-align:center"><div class="sheet-handle"></div><h2>${changing?'تغییر PIN':'انتخاب PIN چهاررقمی'}</h2><p class="hint">PIN پشتیبان را به خاطر بسپار.</p><div class="pin-dots" style="justify-content:center">${'<i></i>'.repeat(4)}</div><div class="keypad" style="margin:auto">${[1,2,3,4,5,6,7,8,9,'',0,'⌫'].map(x=>x===''?'<span></span>':`<button data-key="${x}">${toFa(x)}</button>`).join('')}</div></div></div>`);const sh=document.getElementById('pinSheet'),dots=()=>[...sh.querySelectorAll('.pin-dots i')].forEach((d,i)=>d.classList.toggle('on',i<pin.length));sh.querySelectorAll('[data-key]').forEach(b=>b.onclick=async()=>{const k=b.dataset.key;if(k==='⌫')pin=pin.slice(0,-1);else if(pin.length<4)pin+=k;dots();if(pin.length===4){const salt=b64(randomBytes(16)),hash=await sha256(salt+pin);await kvSet('pin',{salt,hash});sh.remove();toast('PIN ذخیره شد');resolve(true)}})})}
async function verifyPin(pin){const p=await kvGet('pin');if(!p)return false;return (await sha256(p.salt+pin))===p.hash}
async function renderLock(){const hasPin=await kvGet('pin');if(!hasPin){app.innerHTML=`<div class="lock-screen"><div class="brand-mark">م</div><h1>مدیریت مالی</h1><p>اطلاعات فقط روی همین دستگاه ذخیره می‌شوند.<br>برای شروع یک PIN چهاررقمی بساز.</p><button class="primary" id="firstPin" style="margin-top:24px;min-width:210px">ساخت PIN</button></div>`;document.getElementById('firstPin').onclick=async()=>{await setupPin();state.unlocked=true;render()};return}
 const face=await kvGet('faceCredential');app.innerHTML=`<div class="lock-screen"><div class="brand-mark">م</div><h1>مدیریت مالی</h1><p>${face?'با Face ID وارد شو یا PIN را استفاده کن.':'PIN چهاررقمی را وارد کن.'}</p>${face?'<button class="primary" id="faceUnlock" style="margin-top:22px;min-width:210px">باز کردن با Face ID</button>':''}<button class="secondary" id="pinUnlock" style="margin-top:10px;min-width:210px">ورود با PIN</button></div>`;document.getElementById('faceUnlock')?.addEventListener('click',unlockFace);document.getElementById('pinUnlock').onclick=pinUnlockSheet}
function pinUnlockSheet(){let pin='';document.body.insertAdjacentHTML('beforeend',`<div class="sheet-backdrop" id="unlockSheet"><div class="sheet" style="max-width:430px;text-align:center"><div class="sheet-handle"></div><h2>PIN</h2><div class="pin-dots" style="justify-content:center">${'<i></i>'.repeat(4)}</div><div class="keypad" style="margin:auto">${[1,2,3,4,5,6,7,8,9,'',0,'⌫'].map(x=>x===''?'<span></span>':`<button data-key="${x}">${toFa(x)}</button>`).join('')}</div></div></div>`);const sh=document.getElementById('unlockSheet'),dots=()=>[...sh.querySelectorAll('.pin-dots i')].forEach((d,i)=>d.classList.toggle('on',i<pin.length));sh.onclick=e=>{if(e.target===sh)sh.remove()};sh.querySelectorAll('[data-key]').forEach(b=>b.onclick=async()=>{const k=b.dataset.key;if(k==='⌫')pin=pin.slice(0,-1);else if(pin.length<4)pin+=k;dots();if(pin.length===4){if(await verifyPin(pin)){sh.remove();state.unlocked=true;render();dailyGoldUpdate()}else{toast('PIN اشتباه است');pin='';dots()}}})}
async function setupFaceID(){if(!window.PublicKeyCredential||!navigator.credentials){toast('WebAuthn روی این مرورگر در دسترس نیست');return}try{const userId=randomBytes(16),cred=await navigator.credentials.create({publicKey:{challenge:randomBytes(32),rp:{name:'مدیریت مالی'},user:{id:userId,name:'local-user',displayName:'کاربر مدیریت مالی'},pubKeyCredParams:[{type:'public-key',alg:-7},{type:'public-key',alg:-257}],authenticatorSelection:{authenticatorAttachment:'platform',userVerification:'required',residentKey:'preferred'},timeout:60000,attestation:'none'}});await kvSet('faceCredential',{id:b64(new Uint8Array(cred.rawId)),created:new Date().toISOString()});toast('Face ID فعال شد');render()}catch(e){console.error(e);toast('فعال‌سازی Face ID انجام نشد')}}
async function unlockFace(){try{const c=await kvGet('faceCredential');if(!c)return;const cred=await navigator.credentials.get({publicKey:{challenge:randomBytes(32),allowCredentials:[{id:unb64(c.id),type:'public-key',transports:['internal']}],userVerification:'required',timeout:60000}});if(cred){state.unlocked=true;render();dailyGoldUpdate()}}catch(e){console.error(e);toast('Face ID تأیید نشد')}}

async function exportAll(){const out={version:APP_VERSION,exportedAt:new Date().toISOString(),stores:{}};for(const name of STORES){out.stores[name]=await getAll(name);if(name==='kv')out.stores[name]=out.stores[name].filter(x=>x.id!=='faceCredential')}return out}
async function deriveKey(password,salt,usage){const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:180000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,usage)}
async function backupData(){const password=prompt('برای فایل بکاپ یک گذرواژه انتخاب کن (حداقل ۶ کاراکتر):');if(!password||password.length<6)return toast('بکاپ لغو شد یا گذرواژه کوتاه بود');const salt=randomBytes(16),iv=randomBytes(12),key=await deriveKey(password,salt,['encrypt']),plain=new TextEncoder().encode(JSON.stringify(await exportAll())),cipher=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,plain));const payload={format:'mali-backup-v1',salt:b64(salt),iv:b64(iv),data:b64(cipher)};const blob=new Blob([JSON.stringify(payload)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`mali-backup-${todayISO()}.mali`;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);toast('بکاپ رمزگذاری‌شده ساخته شد')}
async function restoreData(file){if(!file)return;const password=prompt('گذرواژه بکاپ را وارد کن:');if(!password)return;try{const payload=JSON.parse(await file.text());if(payload.format!=='mali-backup-v1')throw Error('format');const salt=unb64(payload.salt),iv=unb64(payload.iv),data=unb64(payload.data),key=await deriveKey(password,salt,['decrypt']),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv},key,data),obj=JSON.parse(new TextDecoder().decode(plain));if(!confirm('اطلاعات فعلی با محتوای بکاپ جایگزین شود؟'))return;for(const s of STORES){await clearStore(s);for(const item of (obj.stores[s]||[]))await put(s,item)}toast('بازیابی انجام شد');render()}catch(e){console.error(e);toast('بازیابی ناموفق بود؛ گذرواژه یا فایل را بررسی کن')}}

async function startup(){
 db=await openDB();await seed();const s=await settings();state.month=monthOf(s.startDate)||'1405/07';applyTheme(s.theme);
 if('serviceWorker'in navigator){try{await navigator.serviceWorker.register('./sw.js')}catch(e){console.warn('SW',e)}}
 render();window.addEventListener('online',()=>{toast('اتصال اینترنت برقرار شد');dailyGoldUpdate()});window.addEventListener('offline',()=>toast('برنامه در حالت آفلاین ادامه می‌دهد'));
}
startup().catch(e=>{console.error(e);app.innerHTML='<div class="lock-screen"><h1>خطا در اجرای برنامه</h1><p>مرورگر نتوانست دیتابیس محلی را آماده کند.</p></div>'});
